
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - iam.services.k8s.aws
  resources:
  - policies
  - roles
  verbs:
  - '*'
- apiGroups:
  - kubeflow.org
  resources:
  - profiles
  - profiles/finalizers
  - profiles/status
  verbs:
  - '*'
- apiGroups:
  - platform.kubeflow.org
  resources:
  - configs
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - security.istio.io
  resources:
  - authorizationpolicies
  verbs:
  - '*'
