apiVersion: kubeflow.org/v2alpha1
kind: Profile
metadata:
  name: user
spec:
  # Add fields here
  owner:
    kind: User
    name: user@example.com
  clusterRole: kubeflow-admin
  extraResources:
  - fileName: test-template.yaml
    vars:
      Count: 20
      Material: wood
  - fileName: kfp.yaml
    vars: {}
