apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kubeflow-default-ingress-egress
  namespace: {{ .Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          istio: system
    - namespaceSelector:
        matchLabels:
          app.plural.sh/name: monitoring
      podSelector:
        matchLabels:
          app: prometheus
    - namespaceSelector:
        matchLabels:
          app.plural.sh/name: kubeflow
      podSelector:
        matchLabels:
          app: notebooks-controller
    - namespaceSelector:
        matchLabels:
          app.plural.sh/name: knative
  egress:
  - to:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          istio: system
    - namespaceSelector:
        matchLabels:
          app.plural.sh/name: kubeflow
  - to:
    - namespaceSelector:
        matchLabels:
          kube-system: "true"
    ports:
    - protocol: UDP
      port: 53
